# Properties active for ALL profiles:
---
spring:
  config:
    import: optional:configserver:http://localhost:8001	# Expect the Spring Cloud Config server to be running on localhost, port 8001.
server:
  port: ${PORT:${SERVER_PORT:0}}   # Select any available port if neither port nor server port are specified.

# Allow Eureka to recognize two apps of the same type on the same host as separate instances:
eureka:
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
---
spring:
  profiles:
    active: subject
  application:
    name: lab-5-subject
---
spring:
  profiles:
    active: subject2
  application:
    name: lab-5-subject