---
spring:
  application:
#    name: application
    name: lab-4-subject
  profiles:
    active: subject
  config:
    import: optional:configserver:http://localhost:8001
server:
  port: ${PORT:${SERVER_PORT:0}}
#words: I,You,He,She,It